branches:
  only:
    - master

language: php

php:
- 8.0
- 7.4
- 5.6

cache:
  directories:
    - $HOME/.cache/composer

before_install: composer validate --strict

install:
  - composer validate --strict
  - composer require --no-update --dev roots/wordpress:${WP_VERSION} wp-phpunit/wp-phpunit:${WP_VERSION}
  - "[ $TRAVIS_PHP_VERSION == '8.0' ] || composer install"
  # Temporary hack to allow installing PHPUnit 7 with PHP 8 until WP 5.9.
  # as WP PHPUnit does not allow PHPUnit higher than 7 yet.
  # See https://github.com/WordPress/wordpress-develop/commit/8def694fe4c5df95f8e20e40389faf9cb92b6dca
  - "[ $TRAVIS_PHP_VERSION != '8.0' ] || composer install --ignore-platform-reqs"
  - composer show

script:
  - php -l src/db.php || exit 1
  - composer test
